language: node_js
node_js:
  - "8"
  - "10"
  - "12"

cache:
  directories:
    - node_modules

before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node

script:
  - pnpm install
  - pnpm run test
